application: namebattle
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: django
  version: latest
handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: login.application
- url: /sign
  script: login.application
- url: /select
  script: login.application
- url: /createmain
  script: logincreate.app
- url: /begin
  script: main.app
- url: /titlescreen
  script: title.app
- url: /beginow
  script: onlineGame.app
- url: /nosign
  script: Redirect.app